# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        dc:
          - dmd-latest
          - dmd-2.086.1
          - ldc-latest
        exclude:
          - { os: macOS-latest, dc: dmd-2.086.1 }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Checkout source
        uses: actions/checkout@v2

      - name: 'Build & Test'
        run: |
          # Release build
          dub build --parallel -b release
          dub clean --all-packages -q
          # Run tests
          dub test --root=tests/ --parallel --coverage

      - name: Upload Coverage to Codecov
        # Upload test coverage
        if: runner.os == 'Linux'
        run: bash <(curl -s https://codecov.io/bash)
